targets:
  $default:
    sources:
      - $package$
      - assets/i18n/$i18n$
      - assets/i18n/**.i18n.json
      - lib/$lib$
      - lib/**.dart
      - core/**.dart
      - test/**.dart
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        generate_for:
            - lib/**.codegen.dart
            - core/**.codegen.dart
        options:
          field_rename: snake
      freezed:freezed:
        options:
          make_collections_unmodifiable: false
        generate_for:
            - lib/**/bloc/**.dart
            - lib/**/cubit/**.dart
            - lib/**.codegen.dart
            - core/**.codegen.dart
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/injector.dart
      # slang_build_runner:
      #   options:
      #     import: 'package:slang_build_runner/slang_build_runner.dart'
      #     builder_factories: [ 'i18nBuilder' ]
      #     build_extensions: { '.i18n.json': [ '.g.dart' ] }
      #     build_to: source
      #     auto_apply: root_package
      #     key_case: camel
      #     param_case: camel
      #     base_locale: en
      #     fallback_strategy: base_locale