name: flutter_pos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  alice: ^0.4.2
  auto_route: ^8.3.0
  bloc_concurrency: ^0.2.5
  collection: ^1.18.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  draggable_float_widget: ^0.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_serializable: ^6.9.0
  json_view: ^0.4.2
  mqtt_client: ^10.5.1
  realm: ^20.0.0
  realm_studio_manager:
    git:
      url: https://github.com/ekokurniadi/realm_studio_manager.git
  responsive_builder: ^0.7.0
  responsive_framework: ^0.1.9
  rxdart: ^0.27.0
  sentry_dio: ^8.10.1
  sentry_flutter: ^8.10.1
  shared_preferences: ^2.3.3
  slang: ^4.2.1
  slang_flutter: ^4.2.0

dev_dependencies:
  auto_route_generator: ^8.1.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  husky: ^0.1.7
  injectable_generator: ^2.6.2
  integration_test:
    sdk: flutter
  lint_staged: ^0.5.1
  mockito: ^5.4.4
  realm_common: ^20.0.0
  test: ^1.25.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

coverage:
  exclude:
    - "lib/**/*.schema.realm.dart"

flutter_gen:
  output: lib/gen/assets
  assets:
    outputs:
      directory_path_enabled: true
    exclude:
      - assets/translations/**
      - assets/fonts
  integrations:
    flutter_svg: true
